"""xG (Expected Goals) averages — offense + defense.

Returns None when no match in the input has xG data (e.g., Liga Pro Ecuador
sometimes lacks this — model must downgrade gracefully).
"""

from statistics import mean

from core.features import MatchData


def avg_xg_for(matches: list[MatchData], team_id: int) -> float | None:
    """Average xG generated by team across matches. None if no xG data."""
    xg_values = []
    for match in matches:
        if match.home_team_id == team_id and match.home_xg is not None:
            xg_values.append(match.home_xg)
        elif match.away_team_id == team_id and match.away_xg is not None:
            xg_values.append(match.away_xg)
    return mean(xg_values) if xg_values else None


def avg_xg_against(matches: list[MatchData], team_id: int) -> float | None:
    """Average xG conceded by team. None if no xG data."""
    xg_values = []
    for match in matches:
        if match.home_team_id == team_id and match.away_xg is not None:
            xg_values.append(match.away_xg)
        elif match.away_team_id == team_id and match.home_xg is not None:
            xg_values.append(match.home_xg)
    return mean(xg_values) if xg_values else None


def avg_stat(
    matches: list[MatchData], team_id: int, home_attr: str, away_attr: str,
) -> float | None:
    """Generic average for any stat with home/away pair attributes.

    Example: avg_stat(matches, team_id, 'home_possession', 'away_possession')
    """
    values = []
    for match in matches:
        if match.home_team_id == team_id:
            val = getattr(match, home_attr, None)
        elif match.away_team_id == team_id:
            val = getattr(match, away_attr, None)
        else:
            continue
        if val is not None:
            values.append(float(val))
    return mean(values) if values else None
