"""initial schema with teams matches predictions bets bankroll

Revision ID: 17f709b1b621
Revises: 
Create Date: 2026-05-19 21:44:30.128557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f709b1b621'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_cache',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_data_cache'))
    )
    with op.batch_alter_table('data_cache', schema=None) as batch_op:
        batch_op.create_index('ix_data_cache_expires_at', ['expires_at'], unique=False)

    op.create_table('model_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predictions_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('roi_pct', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('correct_count >= 0 AND correct_count <= predictions_count', name=op.f('ck_model_performance_ck_model_performance_correct_valid')),
    sa.CheckConstraint('predictions_count >= 0', name=op.f('ck_model_performance_ck_model_performance_count_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_performance'))
    )
    with op.batch_alter_table('model_performance', schema=None) as batch_op:
        batch_op.create_index('ix_model_performance_version_period', ['model_version', 'period_start'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('league', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('football_data_id', sa.Integer(), nullable=True),
    sa.Column('sofascore_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("league IN ('PL', 'PD', 'BL1', 'SA', 'FL1', 'CL', 'LIB', 'EC1', 'OTHER')", name=op.f('ck_teams_ck_teams_league')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('slug', 'league', name='uq_teams_slug_league')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_football_data_id'), ['football_data_id'], unique=False)
        batch_op.create_index('ix_teams_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_sofascore_id'), ['sofascore_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(length=20), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=1), nullable=True),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('home_possession', sa.Float(), nullable=True),
    sa.Column('away_possession', sa.Float(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('away_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("league IN ('PL', 'PD', 'BL1', 'SA', 'FL1', 'CL', 'LIB', 'EC1', 'OTHER')", name=op.f('ck_matches_ck_matches_league')),
    sa.CheckConstraint("result IN ('H', 'D', 'A') OR result IS NULL", name=op.f('ck_matches_ck_matches_result')),
    sa.CheckConstraint("source IN ('football_data', 'sofascore', 'manual')", name=op.f('ck_matches_ck_matches_source')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('source', 'external_id', name='uq_matches_source_external_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_away_team_date', ['away_team_id', 'match_date'], unique=False)
        batch_op.create_index('ix_matches_home_team_date', ['home_team_id', 'match_date'], unique=False)
        batch_op.create_index('ix_matches_league_date', ['league', 'match_date'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('league', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('pre_score', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('my_prob', sa.Float(), nullable=False),
    sa.Column('ev', sa.Float(), nullable=False),
    sa.Column('kelly_fraction', sa.Float(), nullable=False),
    sa.Column('quota', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("league IN ('PL', 'PD', 'BL1', 'SA', 'FL1', 'CL', 'LIB', 'EC1', 'OTHER')", name=op.f('ck_predictions_ck_predictions_league')),
    sa.CheckConstraint("verdict IN ('apostar', 'esperar', 'no_apostar')", name=op.f('ck_predictions_ck_predictions_verdict')),
    sa.CheckConstraint('implied_prob >= 0 AND implied_prob <= 100', name=op.f('ck_predictions_ck_predictions_implied_prob_range')),
    sa.CheckConstraint('kelly_fraction >= 0 AND kelly_fraction <= 1', name=op.f('ck_predictions_ck_predictions_kelly_range')),
    sa.CheckConstraint('my_prob >= 0 AND my_prob <= 100', name=op.f('ck_predictions_ck_predictions_my_prob_range')),
    sa.CheckConstraint('pre_score >= 0 AND pre_score <= 100', name=op.f('ck_predictions_ck_predictions_pre_score_range')),
    sa.CheckConstraint('quota > 1', name=op.f('ck_predictions_ck_predictions_quota_positive')),
    sa.CheckConstraint('stake >= 0', name=op.f('ck_predictions_ck_predictions_stake_positive')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_predictions_away_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_predictions_home_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_predictions_match_date', ['match_date'], unique=False)

    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('quota_used', sa.Float(), nullable=False),
    sa.Column('stake_amount', sa.Float(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('payout_amount', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("outcome IN ('pending', 'won', 'lost', 'void')", name=op.f('ck_bets_ck_bets_outcome')),
    sa.CheckConstraint('quota_used > 1', name=op.f('ck_bets_ck_bets_quota_positive')),
    sa.CheckConstraint('stake_amount > 0', name=op.f('ck_bets_ck_bets_stake_positive')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_bets_prediction_id_predictions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bets')),
    sa.UniqueConstraint('prediction_id', name=op.f('uq_bets_prediction_id'))
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index('ix_bets_outcome', ['outcome'], unique=False)

    op.create_table('bankroll_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('change_amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('related_bet_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("reason IN ('deposit', 'withdrawal', 'bet_won', 'bet_lost', 'bet_void', 'adjustment')", name=op.f('ck_bankroll_snapshots_ck_bankroll_snapshots_reason')),
    sa.ForeignKeyConstraint(['related_bet_id'], ['bets.id'], name=op.f('fk_bankroll_snapshots_related_bet_id_bets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bankroll_snapshots'))
    )
    with op.batch_alter_table('bankroll_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bankroll_snapshots_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankroll_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bankroll_snapshots_created_at'))

    op.drop_table('bankroll_snapshots')
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index('ix_bets_outcome')

    op.drop_table('bets')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_predictions_match_date')

    op.drop_table('predictions')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_league_date')
        batch_op.drop_index('ix_matches_home_team_date')
        batch_op.drop_index('ix_matches_away_team_date')

    op.drop_table('matches')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_sofascore_id'))
        batch_op.drop_index('ix_teams_name')
        batch_op.drop_index(batch_op.f('ix_teams_football_data_id'))

    op.drop_table('teams')
    with op.batch_alter_table('model_performance', schema=None) as batch_op:
        batch_op.drop_index('ix_model_performance_version_period')

    op.drop_table('model_performance')
    with op.batch_alter_table('data_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_data_cache_expires_at')

    op.drop_table('data_cache')
    # ### end Alembic commands ###
